### ISSUE TITLE
editing monitors by hand can crash monitor setup

### ISSUE THREAD

**Issue by derammo** [HeliosVirtualCockpit/Helios#360]
using 3306, I edited XML and removed monitors 1 and 2 from a 3 monitor profile, and changed the bindings to refer to monitor 1

on opening the profile it crashed monitor setup

2020-10-02 19:48:27.6903|ERROR|GadrocsWorkshop.Helios.Windows.ExceptionViewer|Unhandled exception occurred. Helios will exit.|System.InvalidOperationException
Cannot call this method on the Empty Rect.
   at System.Windows.Rect.Offset(Double offsetX, Double offsetY)
   at GadrocsWorkshop.Helios.Patching.DCS.MonitorSetupGenerator.ConvertToDCS(Rect& windowsRect)
   at GadrocsWorkshop.Helios.Patching.DCS.MonitorSetupGenerator.<UpdateMonitorSetup>d__9.MoveNext()
   at GadrocsWorkshop.Helios.Patching.DCS.MonitorSetupGenerator.<PerformReadyCheck>d__25.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GadrocsWorkshop.Helios.Patching.DCS.MonitorSetup.InvalidateStatusReport()
   at GadrocsWorkshop.Helios.Interfaces.Common.InterfaceStatusScanner.PerformChecks()
   at GadrocsWorkshop.Helios.Interfaces.Common.InterfaceStatusScanner.Reload(HeliosProfile profile)
   at GadrocsWorkshop.Helios.ProfileEditor.MainWindow.LoadProfile(String path, Boolean suppressLayout)
   at System.Windows.Window.WmActivate(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by derammo** [comment]
as expected, this is a special case of "main monitor is not present but no reset required because existing monitors fit geometry"
