### ISSUE TITLE
Issue launching Helios Control Panel and Profile Editor

### ISSUE THREAD

**Issue by graham24m** [HeliosVirtualCockpit/Helios#376]
When trying launch Helios Control panel or trying to open a profile in the Helios Profile editor, I am getting a Unhandled Error in PresentationFramework. 

I have tried googling the issue to resolve it but no luck.  Suggestion to fix the error listed below
I have double check i am fully updated on Windows 10
Done sfc scannow - no issues
I am on .NET Framework 3.5

![Helios](https://user-images.githubusercontent.com/75397390/100939899-cc803500-3542-11eb-9691-57f679c8a62e.png)

[Control Center Problems.log](https://github.com/HeliosVirtualCockpit/Helios/files/5632443/Control.Center.Problems.log)
[Control Center.log](https://github.com/HeliosVirtualCockpit/Helios/files/5632444/Control.Center.log)

**Comment by derammo** [comment]
we develop for .NET 4.7.2 and I thought the product was making a requirement for that?  I am surprised it is allowing you to run with .NET 3.5.  

I also honestly did not know you could run .NET 3.5 on Windows 10, since I think the oldest version of Windows 10 comes with 4.6 by default?

Are you sure you don't have .NET 3.5 installed and ALSO 4.8.x from windows update?

**Comment by derammo** [comment]
clarification:  It is totally normal to have .NET 3.5 installed in addition to the 4.x that is installed by the OS, if you have applications installed that require the old 3.5

**Comment by derammo** [comment]
@graham24m could you try this please:
https://stackoverflow.com/a/65111729

**Comment by derammo** [comment]
developer  notes:   

XAML loads of icons and bitmaps are done implicitly by the converter from string to image source.  Therefore, we have no code in the path where we could log and/or decide not to crash.

It is an easy change to replace all ImageSource usage with explicit instantiations of an ImageSource of our own that loads, reports exceptions and what source file was involved, and finally just displays a default or nothing.   That would have also made figuring out the AeroWarning crash a lot easier.

**Comment by graham24m** [comment]
Hi Ammo

Thanks that worked

I am on .net 4.8 but a video I watched said to check that box also

the issue in itself is odd my wife changed those settings like 6 months ago and no issue until yesterday

Once again thank you

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by derammo** [comment]
someone else on stack exchange was saying it is caused by a recent windows update so that explains why it suddenly starts happening

**Comment by BlueFinBima** [comment]
> Just had a customer who was facing the described error, setting `image.CreateOptions = BitmapCreateOptions.IgnoreColorProfile` solved the issue.
Lifted from the StackOverflow link above.

**Comment by BlueFinBima** [comment]
Adding exception for searchability
```
2020-12-03 08:24:32.3301|ERROR|GadrocsWorkshop.Helios.Windows.ExceptionViewer|Unhandled exception occurred. Helios will exit.|System.Windows.Markup.XamlParseException
Provide value on 'System.Windows.Baml2006.TypeConverterMarkupExtension' threw an exception.
   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at System.Windows.Application.LoadBamlStreamWithSyncInfo(Stream stream, ParserContext pc)
   at System.Windows.Application.DoStartup()
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.OverflowException
The image data generated an overflow during processing.
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapSource.CreateCachedBitmap(BitmapFrame frame, BitmapSourceSafeMILHandle wicSource, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapPalette palette)
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(BitmapDecoder decoder, ReadOnlyCollection`1 frames)
   at System.Windows.Media.Imaging.BitmapDecoder.get_Frames()
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CallProvideValue(MarkupExtension me, IServiceProvider serviceProvider)
System.ArithmeticException
Overflow or underflow in the arithmetic operation.
```
