### ISSUE TITLE
Helios Error in Loading Profile (1.6.3605.0 & 1.6.5012.0)

### ISSUE THREAD

**Issue by JollyGreenFE** [HeliosVirtualCockpit/Helios#458]
Receiving an error in loading all my profiles.  Of my 3 profiles for DCS & BMS, none of them will open.  It occurred first while using the latest version 1.6.3605 & then occurred again when attempting to use the per-release version 1.6.5012.0.

[Helios_status_report_132771717045816535.txt](https://github.com/HeliosVirtualCockpit/Helios/files/7232447/Helios_status_report_132771717045816535.txt)

Also, when I attempt to open the profiles in the Profile Editor I get a message window stating "Unhandled Error in mscorlib" and the program will close.  See below...

---------------------------
Unhandled Error in mscorlib
---------------------------
Unhandled exception occurred.  Please file a bug:
Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)

   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)

   at System.Version.TryParseVersion(String version, VersionResult& result)

   at System.Version.Parse(String input)

   at GadrocsWorkshop.Helios.Interfaces.Falcon.FalconInterface.set_FalconVersion(String value)

   at GadrocsWorkshop.Helios.Interfaces.Falcon.FalconInterface.ReadXml(XmlReader reader)

   at GadrocsWorkshop.Helios.HeliosSerializer.<DeserializeInterface>d__33.MoveNext()

   at GadrocsWorkshop.Helios.HeliosSerializer.<DeserializeInterfaces>d__36.MoveNext()

   at GadrocsWorkshop.Helios.HeliosSerializer.<DeserializeProfile>d__39.MoveNext()

   at GadrocsWorkshop.Helios.ProfileManager.<LoadingWork>d__6.MoveNext()

   at GadrocsWorkshop.Helios.ProfileEditor.MainWindow.LoadProfile(String path, Boolean suppressLayout)

   at GadrocsWorkshop.Helios.ProfileEditor.MainWindow.OpenProfile()

   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)

   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)

   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)

   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)

   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)

   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)

   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)

   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)

   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)

   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)

   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)

   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
---------------------------
OK   
---------------------------

**Comment by derammo** [comment]
could you attach one failing DCS and one failing BMS profile please?

the BMS one fails in parsing the Falcon interface config, so it would be very interesting to see the DCS profile fail.

don't attach images etc, just the .hpf files

**Comment by JollyGreenFE** [comment]
AFter a re-install & reboot the DCS profile is working as advertised.  As is 4.35 BMS profiles.  

What isn't working now is profiles I used for BMS beta versions.  You can find this particular hpf [HERE](https://1drv.ms/u/s!AtBfAXlM0a2Li_xNvsFPU3_y-eSjww?e=abgsoy).

**Comment by derammo** [comment]
@Todd1215 it's trying to parse this as a "Version" object for no particular reason I can figure.   Should be any string that is a valid directory segment?

```      
<FalconVersion>Falcon BMS 4.36 (Internal)</FalconVersion>
```

**Comment by Todd1215** [comment]
yeah I had intended to compare profile version with installed BMS version for separating what functionality worked in which version of BMS but it was a bust. I will fix the code to  read it as a string
