### ISSUE TITLE
Profile Editor's Simulate Monitor Layout Stored in Current Profile - Unhandled Exception

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#584]
Profile Editor's Tool "Simulate Monitor Layout Stored in Current Profile" in 1.6.5102.0 results in the following exception if the monitor layout defined in the profile does not exist in the group `DCSMonitorSetup` in `HeliosSettings.xml` .  This results in mainView and uiView being empty rectangles.
```
2022-07-12 12:59:22.9813|ERROR|GadrocsWorkshop.Helios.Windows.ExceptionViewer|Unhandled exception occurred. Helios will exit.|System.InvalidOperationException
Cannot call this method on the Empty Rect.
   at System.Windows.Rect.Offset(Double offsetX, Double offsetY)
   at GadrocsWorkshop.Helios.Patching.DCS.MonitorSetupGenerator.ConvertToDCS(Rect& windowsRect)
   at GadrocsWorkshop.Helios.Patching.DCS.MonitorSetupGenerator.<UpdateMonitorSetup>d__9.MoveNext()
   at GadrocsWorkshop.Helios.Patching.DCS.MonitorSetupGenerator.<PerformReadyCheck>d__25.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at GadrocsWorkshop.Helios.Patching.DCS.MonitorSetup.CreateStatusReport()
   at GadrocsWorkshop.Helios.Interfaces.Common.ViewportCompilerInterface`2.InvalidateStatusReport()
   at GadrocsWorkshop.Helios.ProfileEditorTools.SimulatedMonitors.UpdateProfile()
   at GadrocsWorkshop.Helios.ProfileEditorTools.SimulatedMonitors.Simulate()
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by BlueFinBima** [comment]
Fix for empty rectangle being passed to ConvertToDCS in MonitorSetupGenerator when simulate monitor in profile tool is selected.  The main / UI size will the set to the Rendered display size if it is empty.

I also noticed in testing, that the profile was reporting a match with the actual display configuration when the profile only contained a subset of the monitors.  This has been corrected with a test to ensure that the number of monitors in the profile is the same as the number on the system.  Tested to ensure that when `simulate` is used, the profile returns that it matches the system displays.
