### ISSUE TITLE
Unhandled Exception for AdditionalViewports / MonitorSetup from Profile Explorer in Profile Editor 

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#746]
- [X] I have read [Getting Help](https://github.com/HeliosVirtualCockpit/Helios/wiki/Get-Help)
---
### Describe the Helios Issue
Exceptions relating to uri loading for AdditionalViewportsEditor.xaml and MonitorSetupEditor.xaml (both in the patching project) when the interfaces were selected from the Project Explorer were tracked down to the installer deploying an extra Patching.dll in the same directory as the Profile Editor.exe.

### Steps to Reproduce the problem
Steps to reproduce the behaviour:
1.  Profile Explorer
2. Add the Additional Viewports interface (or the DCS Monitor Setup interface)
3. Close the tab for the Additional Viewports interface at the top of the screen 
4. Open the Additional Viewports item in Profile Explorer
5. Unhandled exception

### Expected behavior
No Unhandled exception
### Please complete the following information:
 - Helios Version [ *1.6.6010.2*]

### The problem happened while using 
(place an 'x' between the square brackets for all that apply)
 - [X] Profile Editor
 - [ ] Control Center
 - [ ] Keypress Receiver
 - [ ] Something else (*remember to tell us what it is*)

### Additional context
*  As of this writing, this problem has not shipped in a released Helios (although it is possible that at some point it might)*
```
2023-08-03 17:51:16.3298|ERROR|GadrocsWorkshop.Helios.Windows.ExceptionViewer|Unhandled exception occurred. Helios will exit.|System.Reflection.TargetInvocationException
Exception has been thrown by the target of an invocation.
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at GadrocsWorkshop.Helios.ModuleManager.CreateInterfaceEditor(HeliosInterface item, HeliosProfile profile)
   at GadrocsWorkshop.Helios.ProfileEditor.MainWindow.CreateDocumentEditor(HeliosObject profileObject)
   at GadrocsWorkshop.Helios.ProfileEditor.MainWindow.AddNewDocument(HeliosObject profileObject)
   at GadrocsWorkshop.Helios.ProfileEditor.MainWindow.OpenProfileItem_Executed(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandBinding.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.Input.CommandManager.ExecuteCommandBinding(Object sender, ExecutedRoutedEventArgs e, CommandBinding commandBinding)
   at System.Windows.Input.CommandManager.FindCommandBinding(CommandBindingCollection commandBindings, Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.FindCommandBinding(Object sender, RoutedEventArgs e, ICommand command, Boolean execute)
   at System.Windows.Input.CommandManager.OnExecuted(Object sender, ExecutedRoutedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Input.RoutedCommand.ExecuteImpl(Object parameter, IInputElement target, Boolean userInitiated)
   at GadrocsWorkshop.Helios.ProfileEditor.ProfileExplorerPanel.TreeView_PreviewMouseDoubleClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Control.HandleDoubleClick(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnPreviewMouseDownThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
System.Exception
The component 'GadrocsWorkshop.Helios.Patching.DCS.Controls.AdditionalViewportsEditor' does not have a resource identified by the URI '/Patching;component/dcs/controls/additionalviewportseditor.xaml'.
   at System.Windows.Application.LoadComponent(Object component, Uri resourceLocator)
   at GadrocsWorkshop.Helios.Patching.DCS.Controls.AdditionalViewportsEditor..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
```

**Comment by BlueFinBima** [comment]
Fixed in commit 6e1f40936000cf5f11c3c3320eaf57cae9811629 however this issue is being raised because it is possible that the issue might occur under slightly different circumstances in the future.
