### ISSUE TITLE
NullReferenceException on Visual Control when image changed and deleted outside of Profile Editor

### ISSUE THREAD

**Issue by BlueFinBima** [HeliosVirtualCockpit/Helios#837]
Recreation scenario from @MadKreator37 

Opened a file in PS ( with it also open in helios). Edited a part, saved as a different name. PS asked if I wanted to save is as the original, I clicked no( didn't want to overwrite the original). Helios crashed.

```
2024-09-11 22:17:44.4639|ERROR|GadrocsWorkshop.Helios.Windows.ExceptionViewer|Unhandled exception occurred. Helios will exit.|System.NullReferenceException
Object reference not set to an instance of an object.
   at GadrocsWorkshop.Helios.Controls.Indicator.ConditionalImageRefresh(String imageName)
   at GadrocsWorkshop.Helios.ProfileEditor.MainWindow.ProcessVisualChildren(HeliosVisualCollection visuals, String imageName)
   at GadrocsWorkshop.Helios.ProfileEditor.MainWindow.ProcessVisualChildren(HeliosVisualCollection visuals, String imageName)
   at GadrocsWorkshop.Helios.ProfileEditor.MainWindow.OnActivated(EventArgs e)
   at System.Windows.Window.WmActivate(IntPtr wParam)
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by BlueFinBima** [comment]
@MadKreator37 
I tried to recreate with the following steps.
1. Created a new profile
2. Added an Indicator to the monitor
3. Changed the On Image to 1.png
4. Loaded 1.png into Photoshop
5. changed the image in Photoshop
6. In Photoshop, I used "Save as Copy" to save 2.png
7. In Photoshop, I closed the currently unsaved 1.png.  At the prompt to save, I selected "No"
8. Went back to Profile Editor and selected the Indicator.
9. I did **not** see the   `NullReferenceException`

Can you please clarify the recreation steps.

Thanks

**Comment by MadKreator37** [comment]
Step sequence is correct. However cannot reproduce in newly created profiles or other existing ones. Seems confined to my current CH-47 Profile

**Comment by BlueFinBima** [comment]
Null object is actually the string OffImage for an indicator, and in this instance, it was set as null in the CH-47F SFD gauge.
